import { useState, useEffect } from 'react';
import { FileText, Download, Trash2, RefreshCw, FolderOpen } from 'lucide-react';
import { apiFetch, apiUrl } from '../hooks/useApi';
import type { FileEntry } from '../types/api';

export function FilesView() {
  const [files, setFiles] = useState<FileEntry[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadFiles();
  }, []);

  async function loadFiles() {
    setLoading(true);
    try {
      const data = await apiFetch<FileEntry[]>('/api/files');
      setFiles(data);
    } catch {
      /* load failed */
    }
    setLoading(false);
  }

  async function deleteFile(name: string) {
    try {
      await apiFetch('/api/files/' + encodeURIComponent(name), { method: 'DELETE' });
      loadFiles();
    } catch {
      /* delete failed */
    }
  }

  function downloadFile(file: FileEntry) {
    window.open(apiUrl(file.url), '_blank');
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center h-full">
        <RefreshCw className="animate-spin text-gray-400" size={24} />
      </div>
    );
  }

  return (
    <div className="h-full overflow-y-auto">
      <div className="max-w-4xl mx-auto px-4 py-6 space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-lg font-semibold text-gray-900">Files</h1>
            <p className="text-xs text-gray-500 mt-0.5">{files.length} file{files.length !== 1 ? 's' : ''} generated by agents</p>
          </div>
          <button
            onClick={loadFiles}
            className="p-2 rounded-lg border border-gray-200 hover:bg-gray-50 transition-colors"
          >
            <RefreshCw size={14} className="text-gray-500" />
          </button>
        </div>

        {files.length > 0 ? (
          <div className="bg-white rounded-xl border border-gray-200">
            <div className="divide-y divide-gray-50">
              {files.map((file) => (
                <div key={file.name} className="px-4 py-3 flex items-center justify-between group">
                  <div className="flex items-center gap-3 min-w-0 flex-1">
                    <div className="p-2 bg-gray-50 rounded-lg">
                      <FileText size={16} className="text-gray-400" />
                    </div>
                    <div className="min-w-0 flex-1">
                      <div className="text-sm font-medium text-gray-900 truncate">{file.name}</div>
                      <div className="text-xs text-gray-400">
                        {formatSize(file.size)} &middot; {new Date(file.modified).toLocaleString()}
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                    <button
                      onClick={() => downloadFile(file)}
                      className="p-1.5 rounded-lg text-gray-400 hover:text-blue-600 hover:bg-blue-50 transition-colors"
                      title="Download"
                    >
                      <Download size={14} />
                    </button>
                    <button
                      onClick={() => deleteFile(file.name)}
                      className="p-1.5 rounded-lg text-gray-400 hover:text-red-600 hover:bg-red-50 transition-colors"
                      title="Delete"
                    >
                      <Trash2 size={14} />
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>
        ) : (
          <div className="bg-white rounded-xl border border-gray-200 py-16 text-center">
            <FolderOpen className="mx-auto text-gray-300 mb-3" size={40} />
            <p className="text-sm text-gray-500 mb-1">No files yet</p>
            <p className="text-xs text-gray-400">Files created by agents during tasks will appear here</p>
          </div>
        )}
      </div>
    </div>
  );
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return bytes + ' B';
  if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB';
  return (bytes / (1024 * 1024)).toFixed(1) + ' MB';
}
